(define x 5)
(define y "yeoooo")
(define z '(1 2 3 4))
(define z #\f)
(define a 5.3)
(define b #t)
(define c y)
(define x 6)
(define h 'ws)
(define test '(1 2 3))
(define should_eq_test '(1 . (2 3)))
(define nested_list '(1 2 (3 4)))
(define mixed_elts '(1 #(2 3 (4 5)) #t "yarr" 4))
(define vec '#((1 2) 3 #f "yarr" x (3 4)))
(define boto '(1 2 (1 2)))
(define mate '(21 . 22))
(define lst_symbols '(a b c d))