;(define (func) 5)
;(define (one x y z) (define (two y) y)(define f 5) two)
;(define (monkey a b c d e f g) g)

;(define (one_arg x y) (define (inner z) 8) (inner 1))
;(one_arg 1 2)

;(define (outer) (define (middle) (define (inner) 2)(inner)) (inner))
;(outer)

;(define monkey 21)
;(define (one_arg x) (define f "hey") func)
;(define (my_func one two three four five six seven eight) (define f 7)eight)
;(define yeo '(1 . 2))
;(define (my_func1 x) '(1 2 3 4))
;(define (my_func x) '#((1 2) 3 #f "yarr" x (3 4)))
;(define (func one two three four five six seven . args) args)
;(func)

;(define (monkey x y) x)
;(define (func one two three four five six seven eight) eight)
;(func 1 2 3 4 5 6 7 8)


;(define (yeo x) (display x))
;(yeo 21)
;(yeo '(1 2 3 4 5))
;(yeo '(1 2 #(3 4)))
;(display '(1 2 3))
;(display '#())
;(display '())
;(display #t)
;(define new_display display)
;(new_display 27)
(define (custom func) (func 3))