;(define malecon "hello :D")
;(define y "omg")
;(define z "soul drain")
;(define f 5)
;(define g 6)
(define glob 4.3)
(define (func x y z) (define local "yay") (define foo "foo") z)
(func "oh" "my" "god")

; (define (foo) 
;     (define c "loc")
;     (+ 1 2))
; (foo)