(define malecon "hello :D")
(define y "omg")
(define z "soul drain")
(define f 5)
(define g 6)
;(define (func x y z) (define local "yay")z)
; (define (foo) 
;     (define c "loc")
;     (+ 1 2))
; (foo)